name: TCGstorageAPI build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: TCGstorageAPI_build
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout git submodules
        run: git submodule update --init --recursive 
      - name: Install dependencies 
        run: |
          sudo apt-get update
          sudo apt install python3
          sudo apt install python3-pip
          sudo apt-get install -y --no-install-recommends python3-all python3-all-dev
          sudo apt-get install libgnutls28-dev
          sudo apt-get install libboost-all-dev
      - name: Install python requirement packages
        run: |
          sudo apt-get install python3-setuptools
          pip3 install --no-cache-dir -r requirements.txt
      - name: Link gmake to make
        run: sudo ln -s /usr/bin/make /usr/bin/gmake
      - name: Build opensea
        run: python3 setup.py opensea
      - name: Build TCGstorageAPI package
        run: python3 setup.py build
      - name: Run unit tests
        run: |
          sudo cp -R build/lib.linux-x86_64-3.6/TCGstorageAPI /home/runner/work/TCGstorageAPI/TCGstorageAPI
          export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.6/site-packages/
          python3 TCGstorageAPI/test_tcgapi.py
