name: TCGstorageAPI build

on:
  push:
    branches:
      - master

jobs:
  build:
    # Job name is Greeting
    name: TCGstorageAPI_build
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build 
        run: |
          apt-get update
          apt install python3
          apt install python3-pip
          apt-get install -y --no-install-recommends python3-all python3-all-dev
          apt-get install libgnutls28-dev
          apt-get install libboost-all-dev
          pip3 install --no-cache-dir -r requirements.txt
      - name: Build opensea
        run: python3 setup.py opensea
      - name: Build TCGstorageAPI package
        run: python3 setup.py build
        
        
