name: TCGstorageAPI build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: build
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Checkout
        uses: actions/checkout@v2
      # This step prints an output (time) from the previous step's action.
      - name: Build opensea
        run: python3 setup.py opensea
      - name: Build TCGstorageAPI package
        run: python3 setup.py build
        
