name: TCGstorageAPI build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:
    name: TCGstorageAPI_build
    # This job runs on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout git submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install python3
          sudo apt install python3-pip
          sudo apt-get install -y --no-install-recommends python3-all python3-all-dev
          sudo apt-get install libgnutls28-dev
          sudo apt-get install libboost-all-dev
      - name: Install python requirement packages
        run: |
          sudo apt-get install python3-setuptools
          pip3 install --no-cache-dir -r requirements.txt
      - name: Link libboost_python3 to libboost_python38.so
        run: sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_python38.so /usr/lib/libboost_python3.so
      - name: Build opensea
        run: python3 setup.py opensea
      - name: Build TCGstorageAPI package
        run: python3 setup.py build
      - name: Run unit tests
        run: |
          sudo cp -R build/lib.linux-x86_64-3.8/TCGstorageAPI /home/runner/work/TCGstorageAPI/TCGstorageAPI
          export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.8/site-packages/
          python3 TCGstorageAPI/tcgapi_test.py
